version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - criptext-carthage
      - run: bash ./scripts/intelligent-bootstrap.sh
      - save_cache:
          key: criptext-carthage
          paths:
            - ./Carthage
      - run:
          name: Build and run rests
          command: fastlane scan

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
